const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=__dirname+'/dist/';
function setup(storage={},payload=[],blocked=false){
 const listeners={};class El{constructor(){this.innerHTML='';this.textContent='';this.hidden=false;this.value='';this.checked=false;this.width=1080;this.height=500;this.dataset={};this.style={}}addEventListener(n,f){this[n]=f}focus(){}scrollIntoView(){}setPointerCapture(){}matches(){return false}closest(){return null}getBoundingClientRect(){return{width:1080,height:500,left:0}}getContext(){return new Proxy({createLinearGradient:()=>({addColorStop(){}})},{get:(t,p)=>t[p]||(()=>{}),set:(t,p,v)=>(t[p]=v,true)})}}
 const els=new Map(),get=s=>{if(!els.has(s))els.set(s,new El());return els.get(s)};
 const box={console,Math,JSON,Number,String,Array,Map,Set,Date,Image:class{constructor(){this.complete=false}},HTMLImageElement:El,devicePixelRatio:2,setTimeout,clearTimeout,File:class{},navigator:{vibrate(){},clipboard:{writeText:async()=>{}}},localStorage:{getItem(k){if(blocked)throw Error('blocked');return storage[k]},setItem(k,v){if(blocked)throw Error('blocked');storage[k]=v}},requestAnimationFrame:()=>1,cancelAnimationFrame(){},fetch:async()=>({ok:payload!==null,json:async()=>payload}),AbortSignal,document:{querySelector:get,addEventListener(n,f){listeners[n]=f},createElement:()=>new El(),body:{dataset:{}},hidden:false},window:{AudioContext:class{constructor(){throw Error('audio permission')}},addEventListener(n,f){listeners[n]=f}}};
 vm.createContext(box);const files=['engine.js','sprites.js','heads.js','audio.js','render.js','app.js'];let src=files.map(f=>fs.readFileSync(path+f,'utf8').replaceAll('export ','').replace(/^import[^\n]+\n/gm,'')).join('\n');src+='\nglobalThis.qa={start,choose,menu,pause,resume,gameover,help,leaderboard,loop,doJump,doSlide,resize,actions,releaseControls,get:()=>({state,run,selected,data,collection}),getEl:$};';vm.runInContext(src,box);return{q:box.qa,listeners,box,get,El};
}
const payload=[{id:'1',name:'The Aberration',segment:'Planeswalkers',image:'assets/chimp-1.webp'},{id:'2',name:'The Achromatic',segment:'Proletariat',image:'assets/chimp-2.webp'},{id:'3',name:'The Adolescent',segment:'Proletariat',image:'assets/chimp-3.webp'}];
const advance=(q,start=100,n=40)=>{for(let i=0;i<n;i++)q.loop(start+(i+1)*100)};
(async()=>{const store={};let{q,listeners,box,get,El}=setup(store,payload);await new Promise(r=>setTimeout(r,0));assert.equal(q.get().state,'menu');assert.equal(q.get().collection.length,3);q.choose();const old=q.get().selected.id;q.actions.random();assert.notEqual(q.get().selected.id,old);q.start();advance(q);assert.equal(q.get().state,'running');assert(q.get().run.invulnerable>0,'first run tutorial is non-punishing');
 const key=(code,repeat=false)=>({code,target:{matches:()=>false},repeat,preventDefault(){}});listeners.keydown(key('Space'));assert(q.get().run.jumpHeld);listeners.keydown(key('Space',true));listeners.keyup(key('Space'));assert(!q.get().run.jumpHeld);q.get().run.y=0;q.get().run.vy=0;listeners.keydown(key('KeyW'));assert(q.get().run.jumpHeld);listeners.keyup(key('KeyW'));
 q.get().run.y=0;q.get().run.vy=0;listeners.keydown(key('ShiftLeft'));assert(q.get().run.slideHeld);listeners.keyup(key('ShiftLeft'));assert(!q.get().run.slideHeld);q.get().run.y=0;listeners.keydown(key('ArrowDown'));assert(q.get().run.slideHeld);listeners.keyup(key('ArrowDown'));
 const c=get('#game');c.pointerdown({button:2,pointerType:'mouse',pointerId:7,clientX:400,preventDefault(){}});assert(q.get().run.slideHeld);listeners.pointerup({pointerId:7});c.pointerdown({button:0,pointerType:'mouse',pointerId:8,clientX:800,preventDefault(){}});assert(q.get().run.jumpHeld);listeners.pointerup({pointerId:8});
 q.pause();const frozen=q.get().run.time;q.loop(9000);assert.equal(q.get().run.time,frozen);q.resume();assert.equal(q.get().state,'running');q.get().run.score=600;q.get().run.distance=600;q.gameover();assert.equal(q.get().data.runs[0].score,600);assert(q.get().data.achievements.includes('first-steps'));q.actions.restart();advance(q,10000,15);assert.equal(q.get().state,'running');assert(q.get().run.score<30);assert.equal(q.get().run.bananaCount,0);q.menu();q.help();q.leaderboard();q.choose();get('#overlay').click({target:{closest:()=>({dataset:{fav:'1'}})}});assert(q.get().data.favorites.includes('1'));get('#sound').onclick();q.resize();
 box.document.hidden=true;listeners.visibilitychange();assert(!['running','countdown'].includes(q.get().state));const img=new El();img.src='bad';listeners.error({target:img});assert(img.src.startsWith('data:'));const reload=setup(store,payload);await new Promise(r=>setTimeout(r,0));assert.equal(reload.q.get().data.runs[0].score,600);assert(reload.q.get().data.favorites.includes('1'));
 const fail=setup({},null,true);await new Promise(r=>setTimeout(r,0));assert.equal(fail.q.get().collection.length,3);fail.q.start();advance(fail.q);assert.equal(fail.q.get().state,'running');console.log('PASS UI: migration/save fallback, menu/collection/search/favorites/random, countdown/restart, jump+slide keyboard/mouse, held-input release, pause/tab freeze, achievements, image/audio/storage/collection failure recovery, resize');
})().catch(e=>{console.error(e);process.exitCode=1});
