const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=__dirname+'/dist/';
function setup(storage={},payload=[],blocked=false,assetsReady=false){
 const listeners={};class El{constructor(){this.innerHTML='';this.textContent='';this.hidden=false;this.value='';this.checked=false;this.width=1080;this.height=500;this.dataset={};this.style={}}addEventListener(n,f){this[n]=f}focus(){}scrollIntoView(){}setPointerCapture(){}matches(){return false}closest(){return null}getBoundingClientRect(){return{width:1080,height:500,left:0}}getContext(){return new Proxy({createLinearGradient:()=>({addColorStop(){}})},{get:(t,p)=>t[p]||(()=>{}),set:(t,p,v)=>(t[p]=v,true)})}}
 const els=new Map(),get=s=>{if(!els.has(s))els.set(s,new El());return els.get(s)};
 const box={console,Math,JSON,Number,String,Array,Map,Set,Date,Image:class{constructor(){this.complete=assetsReady;this.naturalWidth=assetsReady?256:0;this.naturalHeight=assetsReady?256:0;this.width=assetsReady?256:0;this.height=assetsReady?256:0}},HTMLImageElement:El,devicePixelRatio:2,setTimeout,clearTimeout,File:class{},navigator:{vibrate(){},clipboard:{writeText:async()=>{}}},localStorage:{getItem(k){if(blocked)throw Error('blocked');return storage[k]},setItem(k,v){if(blocked)throw Error('blocked');storage[k]=v}},requestAnimationFrame:()=>1,cancelAnimationFrame(){},fetch:async()=>({ok:payload!==null,json:async()=>payload}),AbortSignal,document:{querySelector:get,addEventListener(n,f){listeners[n]=f},createElement:()=>new El(),body:{dataset:{}},hidden:false},window:{AudioContext:class{constructor(){throw Error('audio permission')}},addEventListener(n,f){listeners[n]=f}}};
 vm.createContext(box);const files=['engine.js','sprites.js','heads.js','audio.js','render.js','app.js'];let src=files.map(f=>fs.readFileSync(path+f,'utf8').replaceAll('export ','').replace(/^import[^\n]+\n/gm,'')).join('\n');src+='\nglobalThis.qa={start,choose,menu,pause,resume,gameover,help,leaderboard,loop,doJump,doSlide,resize,actions,releaseControls,get:()=>({state,run,selected,data,collection}),getEl:$};';vm.runInContext(src,box);return{q:box.qa,listeners,box,get,El};
}
const payload=[{"id":"12","name":"The Archon","image":"assets/chimp-12.webp","segment":"Old World Cult"},{"id":"95","name":"The Heretic","image":"assets/chimp-95.webp","segment":"Planeswalkers"},{"id":"38","name":"The Commodore","image":"assets/chimp-38.webp","segment":"Proletariat"},{"id":"158","name":"The Pioneer","image":"assets/chimp-158.webp","segment":"Future War Pack"},{"id":"166","name":"The Punk","image":"assets/chimp-166.webp","segment":"Proletariat"},{"id":"193","name":"The Street Fighter","image":"assets/chimp-193.webp","segment":"Old World Cult"},{"id":"26","name":"The Bosun","image":"assets/chimp-26.webp","segment":"Old World Cult"},{"id":"3","name":"The Adolescent","image":"assets/chimp-3.webp","segment":"Proletariat"},{"id":"9","name":"The Angsty","image":"assets/chimp-9.webp","segment":"Proletariat"},{"id":"11","name":"The Apologetic","image":"assets/chimp-11.webp","segment":"Proletariat"}];
const advance=(q,start=100,n=50)=>{for(let i=0;i<n;i++)q.loop(start+(i+1)*100)};
(async()=>{const store={};let{q,listeners,box,get,El}=setup(store,payload);await new Promise(r=>setTimeout(r,0));assert.equal(q.get().state,'menu');assert.equal(q.get().collection.length,3);q.choose();assert.equal(q.get().collection.length,10);assert(get('#overlay').innerHTML.includes('UPLOAD YOUR 3D CHARACTER (GLB)'));assert(get('#overlay').innerHTML.includes('disabled'));const old=q.get().selected.id;q.actions.random();assert.notEqual(q.get().selected.id,old);for(let i=0;i<40;i++){q.actions.random();assert(payload.some(c=>c.id===q.get().selected.id),'Random selected a removed character')}q.start();assert.equal(q.get().state,'intro');q.loop(200);assert.equal(q.get().run.time,0,'intro must not advance gameplay');advance(q,100,90);assert.equal(q.get().state,'running');assert.equal(get('#touchControls').hidden,false);assert(q.get().run.invulnerable>0,'first run tutorial is non-punishing');
 const key=(code,repeat=false)=>({code,target:{matches:()=>false},repeat,preventDefault(){}});listeners.keydown(key('Space'));assert(q.get().run.jumpHeld);listeners.keydown(key('Space',true));listeners.keyup(key('Space'));assert(!q.get().run.jumpHeld);q.get().run.y=0;q.get().run.vy=0;listeners.keydown(key('KeyW'));assert(q.get().run.jumpHeld);listeners.keyup(key('KeyW'));
 q.get().run.y=0;q.get().run.vy=0;listeners.keydown(key('ShiftLeft'));assert(q.get().run.slideHeld);listeners.keyup(key('ShiftLeft'));assert(!q.get().run.slideHeld);q.get().run.y=0;listeners.keydown(key('ArrowDown'));assert(q.get().run.slideHeld);listeners.keyup(key('ArrowDown'));
 const c=get('#game');c.pointerdown({button:2,pointerType:'mouse',pointerId:7,clientX:400,preventDefault(){}});assert(q.get().run.slideHeld);listeners.pointerup({pointerId:7});c.pointerdown({button:0,pointerType:'mouse',pointerId:8,clientX:800,preventDefault(){}});assert(q.get().run.jumpHeld);listeners.pointerup({pointerId:8});
 q.pause();const frozen=q.get().run.time;q.loop(9000);assert.equal(q.get().run.time,frozen);q.resume();assert.equal(q.get().state,'running');q.get().run.score=600;q.get().run.distance=600;q.gameover();assert.equal(q.get().data.runs[0].score,600);assert(q.get().data.achievements.includes('first-steps'));q.actions.restart();advance(q,10000,15);assert.equal(q.get().state,'running');assert(q.get().run.score<30);assert.equal(q.get().run.bananaCount,0);q.menu();q.help();q.leaderboard();q.choose();get('#overlay').click({target:{closest:()=>({dataset:{fav:'1'}})}});assert(q.get().data.favorites.includes('1'));get('#sound').onclick();q.resize();
 box.document.hidden=true;listeners.visibilitychange();assert(!['intro','running','countdown'].includes(q.get().state));const img=new El();img.src='bad';listeners.error({target:img});assert(img.src.startsWith('data:'));const reload=setup(store,payload);await new Promise(r=>setTimeout(r,0));assert.equal(reload.q.get().data.runs[0].score,600);assert(reload.q.get().data.favorites.includes('1'));
 const migratedStore={'chimpions-save-v2':JSON.stringify({version:2,selected:'1',favorites:['1','12','193'],recent:['1','95']})};const migrated=setup(migratedStore,payload);await new Promise(r=>setTimeout(r,0));assert.equal(migrated.q.get().selected.id,'12');assert.equal(migrated.q.get().data.favorites.join(','),'12,193');assert.equal(migrated.q.get().data.recent.includes('1'),false);assert.equal(JSON.parse(migratedStore['chimpions-save-v2']).selected,'12');assert.equal(JSON.parse(migratedStore['chimpions-save-v2']).favorites.includes('1'),false);
 const legacyStore={'chimpions-selected':'221'};const legacyMigrated=setup(legacyStore,payload);await new Promise(r=>setTimeout(r,0));assert.equal(legacyMigrated.q.get().selected.id,'12');assert.equal(legacyStore['chimpions-selected'],'12');
 const fail=setup({},null,true);await new Promise(r=>setTimeout(r,0));assert.equal(fail.q.get().collection.length,10);fail.q.start();advance(fail.q,100,90);assert.equal(fail.q.get().state,'running');const loaded=setup({},payload,false,true);await new Promise(r=>setTimeout(r,0));loaded.q.start();loaded.q.resize();advance(loaded.q,100,90);loaded.q.resize();assert.equal(loaded.q.get().state,'running');console.log('PASS UI: 10-character roster, removed-save migration, favorites/random restriction, disabled GLB extension placeholder, menu/collection/search, UFO intro/countdown/restart, jump+slide keyboard/mouse, held-input release, pause/tab freeze, achievements, image/audio/storage/collection failure recovery, loaded-image render smoke, resize');
})().catch(e=>{console.error(e);process.exitCode=1});
